In [2]:
from statsbombpy import sb

In [5]:
sb.competitions()

C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2025-07-28T14:19:20.467348,2025-07-29T16:03:07.355174,2025-07-29T16:03:07.355174,2025-07-28T14:19:20.467348
72,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
73,72,107,International,Women's World Cup,female,False,True,2023,2025-07-14T10:07:06.620906,2025-07-14T10:10:27.224586,2025-07-14T10:10:27.224586,2025-07-14T10:07:06.620906
74,72,30,International,Women's World Cup,female,False,True,2019,2024-08-08T15:57:56.748740,2021-06-13T16:17:31.694,None,2024-08-08T15:57:56.748740

In [7]:
competitions = sb.competitions()
print(competitions.head())

   competition_id  season_id country_name        competition_name  \
0               9        281      Germany           1. Bundesliga
1               9         27      Germany           1. Bundesliga
2            1267        107       Africa  African Cup of Nations
3              16          4       Europe        Champions League
4              16          1       Europe        Champions League

  competition_gender  competition_youth  competition_international  \
0               male              False                      False
1               male              False                      False
2               male              False                       True
3               male              False                      False
4               male              False                      False

  season_name               match_updated           match_updated_360  \
0   2023/2024  2024-09-28T20:46:38.893391  2025-07-06T04:26:07.636270
1   2015/2016  2024-05-19T11:11:14.192381                        None
2        2023  2024-09-28T01:57:35.846538                        None
3   2018/2019  2025-05-08T15:10:50.835274     2021-06-13T16:17:31.694
4   2017/2018  2024-02-13T02:35:28.134882     2021-06-13T16:17:31.694

          match_available_360             match_available
0  2025-07-06T04:26:07.636270  2024-09-28T20:46:38.893391
1                        None  2024-05-19T11:11:14.192381
2                        None  2024-09-28T01:57:35.846538
3                        None  2025-05-08T15:10:50.835274
4                        None  2024-02-13T02:35:28.134882

C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [8]:
la_liga = competitions[competitions['competition_name'] == "La Liga"]
print(la_liga)

    competition_id  season_id country_name competition_name  \
38              11         90        Spain          La Liga
39              11         42        Spain          La Liga
40              11          4        Spain          La Liga
41              11          1        Spain          La Liga
42              11          2        Spain          La Liga
43              11         27        Spain          La Liga
44              11         26        Spain          La Liga
45              11         25        Spain          La Liga
46              11         24        Spain          La Liga
47              11         23        Spain          La Liga
48              11         22        Spain          La Liga
49              11         21        Spain          La Liga
50              11         41        Spain          La Liga
51              11         40        Spain          La Liga
52              11         39        Spain          La Liga
53              11         38        Spain          La Liga
54              11         37        Spain          La Liga
55              11        278        Spain          La Liga

   competition_gender  competition_youth  competition_international  \
38               male              False                      False
39               male              False                      False
40               male              False                      False
41               male              False                      False
42               male              False                      False
43               male              False                      False
44               male              False                      False
45               male              False                      False
46               male              False                      False
47               male              False                      False
48               male              False                      False
49               male              False                      False
50               male              False                      False
51               male              False                      False
52               male              False                      False
53               male              False                      False
54               male              False                      False
55               male              False                      False

   season_name               match_updated           match_updated_360  \
38   2020/2021  2025-01-29T17:39:28.924386  2025-01-29T18:09:18.620699
39   2019/2020  2024-12-16T16:51:06.833054     2021-06-13T16:17:31.694
40   2018/2019  2024-09-22T18:50:23.364757  2021-07-09T14:53:22.103024
41   2017/2018  2025-07-14T10:01:16.674864     2021-06-13T16:17:31.694
42   2016/2017  2025-03-09T16:03:54.962718     2021-06-13T16:17:31.694
43   2015/2016  2025-04-23T13:59:22.835792     2021-06-13T16:17:31.694
44   2014/2015  2025-06-24T13:39:01.068680     2021-06-13T16:17:31.694
45   2013/2014  2025-06-24T09:52:44.048585     2021-06-13T16:17:31.694
46   2012/2013  2025-06-24T13:53:14.047130     2021-06-13T16:17:31.694
47   2011/2012  2025-06-24T13:38:10.764259     2021-06-13T16:17:31.694
48   2010/2011  2025-06-24T13:51:54.910296     2021-06-13T16:17:31.694
49   2009/2010  2025-06-24T13:43:36.379754     2021-06-13T16:17:31.694
50   2008/2009  2025-06-24T13:52:04.679206     2021-06-13T16:17:31.694
51   2007/2008  2025-06-24T13:47:07.137835     2021-06-13T16:17:31.694
52   2006/2007  2025-06-24T13:52:50.824119     2021-06-13T16:17:31.694
53   2005/2006  2025-06-24T14:05:07.849675     2021-06-13T16:17:31.694
54   2004/2005  2025-06-24T13:48:43.998096     2021-06-13T16:17:31.694
55   1973/1974  2023-07-06T12:50:48.807820                        None

           match_available_360             match_available
38  2025-01-29T18:09:18.620699  2025-01-29T17:39:28.924386
39                        None  2024-12-16T16:51:06.833054
40                        None  2024-09-22T18:50:23.364757
41                        None  2025-07-14T10:01:16.674864
42                        None  2025-03-09T16:03:54.962718
43                        None  2025-04-23T13:59:22.835792
44                        None  2025-06-24T13:39:01.068680
45                        None  2025-06-24T09:52:44.048585
46                        None  2025-06-24T13:53:14.047130
47                        None  2025-06-24T13:38:10.764259
48                        None  2025-06-24T13:51:54.910296
49                        None  2025-06-24T13:43:36.379754
50                        None  2025-06-24T13:52:04.679206
51                        None  2025-06-24T13:47:07.137835
52                        None  2025-06-24T13:52:50.824119
53                        None  2025-06-24T14:05:07.849675
54                        None  2025-06-24T13:48:43.998096
55                        None  2023-07-06T12:50:48.807820

In [17]:
matches = sb.matches(competition_id=11, season_id=1)

C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [18]:
real_madrid_matches = matches[
    (matches['home_team'] == "Real Madrid") |
    (matches['away_team'] == "Real Madrid")
]

print(real_madrid_matches.head())

    match_id  match_date      kick_off      competition     season  \
2       9924  2018-05-06  20:45:00.000  Spain - La Liga  2017/2018
10      9736  2017-12-23  13:00:00.000  Spain - La Liga  2017/2018

      home_team    away_team  home_score  away_score match_status  ...  \
2     Barcelona  Real Madrid           2           2    available  ...
10  Real Madrid    Barcelona           0           3    available  ...

           last_updated_360 match_week competition_stage  \
2   2021-06-13T16:17:31.694         36    Regular Season
10  2021-06-13T16:17:31.694         17    Regular Season

                      stadium                             referee  \
2            Spotify Camp Nou  Alejandro José Hernández Hernández
10  Estadio Santiago Bernabéu                                 NaN

               home_managers             away_managers data_version  \
2   Ernesto Valverde Tejedor           Zinédine Zidane        1.1.0
10           Zinédine Zidane  Ernesto Valverde Tejedor        1.1.0

   shot_fidelity_version xy_fidelity_version
2                      2                   2
10                     2                None

[2 rows x 22 columns]

In [11]:
la_liga = competitions[
    (competitions['competition_name'] == "La Liga") &
    (competitions['season_name'] == "2017/2018")
]

print(la_liga)

    competition_id  season_id country_name competition_name  \
41              11          1        Spain          La Liga

   competition_gender  competition_youth  competition_international  \
41               male              False                      False

   season_name               match_updated        match_updated_360  \
41   2017/2018  2025-07-14T10:01:16.674864  2021-06-13T16:17:31.694

   match_available_360             match_available
41                None  2025-07-14T10:01:16.674864

In [23]:
all_matches =[]
for match_id in sb.matches(competition_id=1267, season_id=107).match_id:
    temp_match = sb.events(match_id=match_id)
    all_matches.append(temp_match)

C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Danish\miniconda3\envs\myenv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [24]:
import pandas as pd
df =pd.concat(all_matches)

In [25]:
df.player.unique()

array([nan, 'Ademola Lookman', 'William Troost-Ekong',
       'Calvin Bassey Ughelumba', 'Oluwasemilogo Adesewo Ibidapo Ajayi',
       'Yahia Fofana', 'Obite Evan Ndicka', 'Ghislain Konan',
       'Odilon Kossonou', 'Simon Adingra', 'Zaidu Sanusi', 'Alex Iwobi',
       'Victor James Osimhen', 'Samuel Chimerenka Chukwueze',
       'Temitayo Olufisayo Olaoluwa Aina', 'Frank Onyeka',
       'Jean Michaël Seri', 'Serge Aurier', 'Stanley Bobo Nwabali',
       'Seko Fofana', 'Max-Alain Gradel', 'Franck Yannick Kessié',
       'Sébastien Haller', 'Moses Daddy-Ajala Simon',
       'Wilfried Stephane Singo', 'Oumar Diakité',
       'Kelechi Promise Iheanacho', 'Alhassan Yusuf', 'Joe Aribo',
       'Ibrahim Sangaré', 'Terem Igobor Moffi', 'Jean-Philippe Krasso',
       'Jean Thierry Lazare Amani', 'Grady Diangana',
       'Samuel Moutoussamy', 'Khuliso Johnson Mudau',
       'Simon Bokote Banza', 'Nkosinathi Sibisi', 'Ronwen Williams',
       'Siyanda Xulu', 'Evidence Makgopa', 'Teboho Mokoena',
       "Sphephelo S''Miso Sithole", 'Themba Zwane',
       'Mihlali Samson Mayambela', 'Aubrey Maphosa Modiba',
       'Silas Katompa Mvumpa', 'Dylan Batubinsika', 'Joris Kayembe Ditu',
       "Théo Bongonda Mbul''Ofeko Batombo", 'Brian Jephte Bayeye',
       'Aaron Tshibola', 'Chancel Mbemba Mangulu', 'Dimitry Bertaud',
       'Thapelo James Morena', 'Meschak Elia', 'Omenuke Mfulu',
       'Thabang Amod Monare', 'Oswin Reagan Appollis', 'Yoane Wissa',
       'Terrence Mashego', 'Fiston Kalala Mayele', 'Cédric Bakambu',
       'Zakhele Lerato Lepasa', 'Henoc Inonga Baka', 'Arthur Masuaku',
       'Gaël Kakuta', 'Willy Boly', 'Lionel Mpasi-Nzau',
       'Gedeon Kalulu Kyatengwa', 'Charles Pickel', 'Jonathan Bamba',
       'Jeremie Boga', 'Mothobi Mvala', 'Bright Osayi-Samuel',
       'Gomolemo Grant Kekana', 'Percy Tau', 'Kenneth Josiah Omeruo',
       'Habibou Mouhamadou Diallo', 'Abdou Diallo', 'Lamine Camara',
       'Ismail Jakobs', 'Moussa Niakhate', 'Pape Matar Sarr',
       'Kalidou Koulibaly', 'Krépin Diatta', 'Sadio Mané',
       'Edouard Mendy', 'Ismaïla Sarr', 'Nicolas Pépé', 'Nicolas Jackson',
       'Christian Kouamé', 'Idrissa Gueye', 'Iliman Ndiaye',
       'Cheikh Ahmadou Bamba Mbacke Dieng', 'Mohamed Bayo', 'Mory Konaté',
       'Mouctar Diakhaby', 'Amadou Diawara', 'Issiaga Sylla',
       'Julian Jeanvier', 'Ibrahim Diakité', 'Aguibou Camara',
       'Morgan Guilavogui', 'Jesús Lázaro Owono Ngua Akeng',
       'Ibán Salvador Edu', 'Jannick Buyla Sam', 'Sekou Oumar Sylla',
       'Esteban Obiang Obono', 'Carlos Akapo Martínez', 'Ibrahim Kone',
       'Federico Bikoro Akieme Nchama', 'Pablo Ganet Cómitre',
       'Basilio Ndong Owono Nchamaaa', 'Saúl Basilio Coco-Bassey Oubiña',
       'Emilio Nsue López', 'José Ndong Machín Dicombo',
       'Serhou Guirassy', 'François Kamano', 'Naby Deco Keïta',
       'Luis Miguel Nlavo Asue', 'Lassine Sinayoko', 'Sikou Niakate',
       'Falaye Sacko', 'Kamory Doumbia', 'Lassana Coulibaly',
       'Diadie Samassekou', 'Hamari Traoré', 'Djigui Diarra',
       'Boubakar Kouyate', 'Adama Traoré', 'Amadou Haïdara',
       'Fousseni Diabaté', 'Nene Dorgeles', 'Boubacar Traore',
       'Mamadou Fofana', 'Yves Bissouma', 'Ibrahim Sissoko',
       'Jovane Eduardo Borges Cabral', 'Roberto Lopes', 'Logan Costa',
       'Kenny Rocha Santos', 'Jamiro Gregory Monteiro Alvarenga',
       'Steven Moreira', 'Kevin Lenini Gonçalves Pereira de Pina',
       'João Paulo Moreira Fernandes', 'Ryan Isaac Mendes da Graça',
       'Josimar José Évora Dias', 'Garry Mendes Rodrigues',
       'Willy Afonso Semedo Johnson', 'Erickson Patrick Correia Andrade',
       'Thapelo Maseko', 'Tiago Manuel Dias Correia', 'Laros Duarte',
       'Jayden Adams', 'Gilson Benchimol Tavares', 'Nyiko Mobbie',
       'Bryan Silva Teixera', 'Mohamed Camara', 'Bertrand Isidore Traoré',
       'Ibrahim Blati Touré', 'Ismahila Ouédraogo', 'Steeve Yago',
       'Mohamed Konaté', 'Abdoul Fessal Tapsoba', 'Issoufou Dayo',
       'Issa Kabore', 'Gustavo Fabrice Sangaré', 'Edmond Fayçal Tapsoba',
       'Kouakou Herve Koffi', 'Adamo Nagalo', 'Cédric Badolo',
       'Sacha Jordan Bansé', 'Sekou Koita',
       'Dango Aboubacar Faissal Ouattara', 'Stephane Aziz Ki',
       'Abdoulaye Touré', 'Facinet Conte', 'Antoine Conte',
       'Signori Dominique Nymi António', 'Eddie Marcos Melo Afonso',
       'Kialonda Gaspar', 'Alfredo Kulembe Ribeiro',
       'Deivi Miguel Vieira', 'Manuel Luís da Silva Cafumana',
       'Augusto de Jesus Corte Real Carneiro', 'Jonathan Buatu Mananga',
       'Valdomiro Tualungo Paulo Lameiras',
       'Cristóvão Paciência Mabululo', 'Jacinto Muondo Dala',
       'Ambrosini Antonio Cabaça Salvador',
       'Bruno Lourenço Pinto de Almeida Paz',
       'Zito André Sebastião Luvumbo', 'Jérémy Bela',
       'Felicio Mendes Joao Milson', 'Paul Onuachu', 'Ivan Kamberipa',
       'Ngero Kaanjuka Katua', 'Lloyd Junior Kazapua', 'Lubeni Haukongo',
       'Kennedy Amutenya', 'Bethuel Muzeu', 'Deon Hotto Kavendji',
       'Adilson Cipriano da Cruz', 'Aprocious Petrus', 'Riaan Hanamub',
       'Prins Menelik Tjiueza', 'Peter Shalulile', 'Absalom Iimbondi',
       'Petrus Shitembi', 'Ananias Gebhardt', 'Uetuuru Kambato',
       'Manuel Keliano', 'Sofyan Amrabat', 'Nayef Aguerd', 'Romain Saïss',
       'Noussair Mazraoui', 'Achraf Hakimi Mouh', 'Azzedine Ounahi',
       'Selim Amallah', 'Amine Adli', 'Yassine Bounou',
       'Abdessamad Ezzalzouli', 'Youssef En-Nesyri', 'Ismael Saibari',
       'Amine Harit', 'Yahia Attiyat allah', 'Ayoub El Kaabi',
       'Babacar Niasse', 'Bodda Mouhsine', 'Hemeya Tanjy', 'Khadim Diaw',
       'Omaré Gassama', 'Ibrahima Keita', 'El Hacen Houeibib',
       'Lamine Ba', 'Souleymane Anne', 'Sidi Bouna Sidi Amar',
       'Deroy Duarte', 'Aboubakary Koita', 'Guessouma Fofana',
       'Pape Ibnou Bâ', 'Yassin Cheikh El Welly', 'El-Hadji Ba',
       'Aboubakar Kamara', 'Ahmed Sayed',
       'Ahmed Elsayed Ali Elsayed Hegazy', 'Marwan Attia Fahim Ghallab',
       'Mostafa Mohamed Ahmed Abdallah', 'Hamdi Fathi',
       'Ahmed Mohamed Abo El Fotouh Mohamed',
       'Mohamed Naser Elsayed Elneny', 'Mahmoud Ibrahim Hassan',
       'Mohamed Hany Gamal Eldemerdash', 'Mohamed Abougabal',
       'Mohamed Abdel Monem', 'Mohamed Hamdy Sharaf', 'Mahmoud Hamada',
       'Omar Marmoush', 'Mostafa Fathi', 'Omar Kamal Abdel Wahed',
       'Mohanad Mostafa Lasheen', 'Jules Olivier Ntcham',
       'André-Frank Zambo Anguissa', 'Jean-Charles Castelletto',
       'Nicolas Moumi Ngamaleu', 'Karl Brillant Toko Ekambi',
       'Oumar Gonzalez', 'Christopher Wooh', 'Joseph Fabrice Ondoa Ebogo',
       'Nouhou Tolo', 'Frank Magri', 'Georges-Kévin Nkoudou Mbida',
       'Francis Odinaka Uzoho', 'Vincent Paté Aboubakar',
       'Enzo Gianni Tchato Mbiayi', 'Faris Pemi Moumbagna', 'Denis Odoi',
       'Alexander Djiku', 'Richard Ofori Antwi', 'Mohamed Salisu',
       'Majeed Ashimeru', 'Mohamed El Sayed Mohamed El Shenawy Gomaa',
       'Jordan Ayew', 'Emam Ashour Metwally Abdelghany',
       'Salis Abdul Samed', 'Iñaki Williams Arthuer', 'Mohamed Salah',
       'Antoine Semenyo', 'Gideon Mensah', 'Mohammed Kudus',
       'Iddrisu Baba Mohammed', 'Osman Bukari', 'Elisha Owusu',
       'Joseph Paintsil', 'Alejandro Balboa Bandeira',
       'Santiago Eneme Bocari', 'José Nabil Onva Adjugu', 'Alfons Amade',
       'Witiness Chimoio João Quembo', 'Domingos João Macandza',
       'Edson André Sitoe', 'Ernan Alberto Siluane',
       'Edmilson Gabriel Dove', 'Stanley Ratifo',
       'Gildo Lourenço Vilanculos', 'Reinildo Isnard Mandava',
       'Ricardo Martins Guimarães', 'Elias Gaspar Pelembe',
       'Bruno Alberto Langa', 'Clésio Bauque', 'Pachoio Lau Há King',
       'Amade Momade', 'Feliciano João Jone', 'Ahmed Hassan Mahgoub',
       'Ransford Königsdörffer', 'Ernest Appiah Nuamah',
       'André Ayew Pelé', 'Yunis Abdelhamid', 'Sofiane Boufal',
       'Lubambo Musonda', 'Emmanuel Justine Rabby Banda', 'Hakim Ziyech',
       'Tresford Lawrence Mulenga', 'Stopilla Sunzu', 'Frankie Musonda',
       'Tandi Mwape', 'Kennedy Musonda', 'Lameck Banda',
       'Edward Chilufya', 'Miguel Changa Chaiwa', 'Patson Daka',
       'Amir Richardson', 'Kings Kangwa', 'Fashion Sakala',
       'Tarik Tissoudali', 'Cletous Chama', 'Bilal El Khannous',
       'Mbwana Ally Samatta', 'Faisal Salum Abdalla', 'Lusajo Mwaikenda',
       'Bakari Nondo Mwamnyeto', 'Ibrahim Abdallah Hamad',
       'Mohamed Hussein Mohamed', 'Haji Mnoga', 'Simon Happygod Msuva',
       'Novatus Dismas Miroshi', 'Himid Mao Mkami', 'Aishi Manula',
       'Mzamiru Yassin', 'Morice Michael Abraham', "Charles M'Mombwa",
       'Denis Kibu', 'Youssoufou Niakaté', 'Aliou Dieng', 'Moussa Diarra',
       'Amadou Dante', 'Vetunuavi Charles Hambira', 'Marcel Papama',
       'Wajdi Kechrida', 'Yassine Meriah', 'Montassar Omar Talbi',
       'Aïssa Bilal Laïdouni', 'Ellyes Joris Skhiri', 'Seifeddine Jaziri',
       'Mohamed Elias Achouri', 'Hamza Rafia', 'Ali Abdi',
       'Bechir Ben Said', 'Anis Ben Slimane', 'Youssef Msakni',
       'Sayfallah Ltaief', 'Naïm Sliti', 'Haythem Jouini',
       'Mohamed Ali Ben Romdhane', 'Baghdad Bounedjah', 'Houssem Aouar',
       'Ramiz Larbi Zerrouki', 'Hichem Boudaoui', 'Aïssa Mandi',
       'Mohamed Amine Tougai', 'Rayan Aït Nouri',
       'Mohamed El Amine Amoura', 'Youcef Atal', 'Mohamed Dellahi Yali',
       'Anthony Louis Mandréa', 'Adam Ounas', 'Idrissa Thiam',
       'Riyad Mahrez', 'Nabil Bentaleb', 'Mohamed Youcef Belaïli',
       'Islam Slimani', 'Bakari Camara', 'Kévin Daniel Van Den Kerkhof',
       'Joaquim Marcos Cunga Balanga', 'Abdoul Razack Guiebre',
       'Djibril Cheick Ouattara', 'Boureima Hassane Bandé', 'Ali Sowe',
       'Musa Barrow', 'Yusupha Bobb', 'Omar Colley', 'Baboucarr Gaye',
       'Alasana Manneh', 'Jacob Mendy', 'Yankuba Minteh', 'Ablie Jallow',
       'Muhammed Sanneh', 'James Gomez', 'Darlin Zidane Yongwa Ngameni',
       'Bubacarr Sanneh', 'Alieu Fadera', 'Assan Ceesay',
       'Olivier Michel Kemen', 'Ebrima Colley', 'Harold Moukoudi',
       'Saidy Janko', 'Nampalys Mendy', 'Abdoulaye Seck', 'Pape Gueye',
       'Saidou Sow', 'Mohamed Aly Camara', 'Moriba Kourouma Kourouma',
       'Cheikhou Kouyaté', 'Idrissa Gana Gueye', 'Seydouba Cisse',
       'Karim Cissé', 'Fodé Ballo Touré',
       'Edilson Alberto Monteiro Sanches Borges',
       'Dylan Tavares dos Santos', 'Carlos Miguel Pereira Fernandes',
       'Mahmoud Abdul Monem Abdelhamid Soliman',
       'Infren Da Conceição David Matola',
       'Ivane Carminio Francisco Urrubal', 'Geny Cipriano Catamo',
       'Alidu Seidu', 'Daniel Amartey', 'Shaquille Momad Nangy',
       'João José Jone Bonde', 'Janio Bikel Figueiredo Silva',
       'Famana Quizera', 'Zinho Gano', 'Houboulang Mendes',
       'Jonas Asvedo Mendes', 'Fernando de Lacerda Gomes',
       'Edgar Miguel Ié', 'Opa Sangante', 'Eulânio Ângelo Chipela Gomes',
       'Euciodálcio Gomes', 'Carlos Mendes Gomes', 'Franculino Gluda Djú',
       'Marciano Sanca Tchami', 'Raphael Onyedika', 'José Correia',
       'Fali Candé', 'Alfa Semedo Esteves', 'Chidozie Collins Awaziem',
       'José Antonio Miranda Boacho', 'Karim Konaté',
       'Juan José Óscar Siafá Etoha', 'Ryan Nyambe', 'Joslin Kamatuka',
       'Wendell Rudath', 'Kelvin Kapumbu', 'Roderick Kabwe',
       'Benedict Chepeshi', 'Mudathiri Yahya', 'Mohamed Chibi',
       'Bassem Srarfi', 'Nouh Mohamed El Abd', 'Yacoub Aly Abeid',
       'Núrio Domingos Matias Fortuna', 'Souleymane Doukara',
       'Ramy Bensebaini', 'Adama Guira', 'Sofiane Feghouli',
       'Fares Chaïbi', 'Dramane Salou', 'Yacouba Nasser Djiga',
       'Noah Sonko-Sundberg', 'Ebrima Darboe', 'Hamza Barry',
       'José Kanté Martínez', 'Muhammed Badamosi', 'Yvan Neyou Noupa',
       'André Onana', 'Junior Tchamadeu', 'Ousmane Diomande',
       'Moreto Moro Cassamã', 'Jefferson Anilson Silva Encada',
       'Marcelo Amado Djaló Taritolay', 'Manconi Soriano Mané',
       'Mama Samba Baldé', 'Mauro Daniel Rodrigues Teixeira',
       'Ouparine Djoco', 'Marvin José Anieboh Pallaruelo',
       'Carlos Manuel Cardoso Mané', 'Noé Ela Mangue', 'Larry Bwalya',
       'Tarryn Allarakhia', 'Ali Maâloul', 'Taha Yassine Khenissi',
       'Mamady Alex Bangré', 'Oumar Ngom', 'Aboubacar Traoré',
       'Ismael Bennacer', 'Loide António Augusto', 'Ibou Touray',
       'Ebou Adams', 'Pathé Ismaël Ciss', 'Abdulia Sanyang',
       'Idrissa Doumbia'], dtype=object)

In [26]:
df = df[df['player'] == 'André Onana']

In [27]:
df.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,shot_redirect,goalkeeper_shot_saved_to_post,shot_saved_to_post,pass_straight,shot_open_goal,goalkeeper_punched_out,goalkeeper_shot_saved_off_target,shot_saved_off_target,player_off_permanent,block_save_block
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.shape

(88, 111)